# Machine-global config

[plugins]
lua-bin = "https://github.com/supermomonga/mise-plugin-lua-bin"

[tools]
# Runtime
bun = "latest"
deno = "latest"
go = "latest"
node = "latest"
python = "latest"
rust = "latest"
zig = "latest"
# for Neovim compatibility, use v5.1
lua = { version = "5.1", os = ["linux", "macos"] }
lua-bin = { version = "5.1", os = ["windows"] }

# Tools
fzf = "latest"
neovim = "latest"
ripgrep = "latest"
starship = "latest"
tree-sitter = "latest"
uv = "latest"
yazi = "latest"
jq = "latest"
yq = "latest"
aws-cli = "latest"

# Packages
"cargo:pik" = "latest"
"cargo:ultraman" = { version = "latest", os = ["linux", "macos"] }
"github:sijiaoh/pockode" = { version = "latest", os = ["linux", "macos"] }
"github:lightpanda-io/browser" = { version = "latest", os = ["linux", "macos"] }
"github:corrupt952/tmuxist" = { version = "latest", os = ["linux", "macos"] }
"github:prskr/git-age" = "latest"
"github:railwayapp/railpack" = "latest"
"go:github.com/babarot/gomi" = "latest"
"go:github.com/k1LoW/git-wt" = "latest"
# temporary disabled.
# use `go install github.com/syou6162/cchook@latest` instead.
# ref: https://github.com/jdx/mise/discussions/6737
#"go:github.com/syou6162/cchook" = "latest"
"go:github.com/Warashi/cage" = { version = "latest", os = ["linux", "macos"] }
"go:github.com/x-motemen/ghq" = "latest"
"npm:@openai/codex" = "latest"
"npm:agent-browser" = "latest"
"npm:opencode-ai" = "latest"
"npm:rulesync" = "latest"
"npm:sentry" = "latest"
"npm:yepanywhere" = "latest"
"pipx:arxivterminal" = "latest"
"pipx:llmstxt2skill" = "latest"
"pipx:edge-tts" = "latest"



[settings]
experimental = true
trusted_config_paths = [
    "~/ghq",
]

[settings.npm]
package_manager = "bun"

[env]
# v3.13.0 broken now https://github.com/luarocks/luarocks/issues/1851
LUAROCKS_VERSION = "3.12.2"

[tasks.sync-rule]
description = "Sync agents' rules from claude code to others"
run = 'rulesync import -t claudecode -f "*" -V; rulesync generate -t "codexcli,opencode" -f "*" -V'

[tasks.sync-rule-global]
description = "Sync agents' rules from claude code to others"
run = 'rulesync import -g -t claudecode -f "*" -V; rulesync generate -g -t "codexcli,opencode" -f "*" -V'
