# Machine-global config

[tools]
# Runtime
bun = "latest"
deno = "latest"
go = "latest"
node = "latest"
python = "latest"
rust = "latest"
zig = "latest"
lua = "5.1" # for Neovim compatibility

# Tools
chezmoi = "latest"
neovim = "latest"
fzf = "latest"
uv = "latest"
tree-sitter = "latest"
yazi = "latest"
starship = "latest"

# Packages
"cargo:pik" = "latest"
"cargo:ultraman" = "latest"
"github:sijiaoh/pockode" = { version = "latest", os = ["linux", "macos"] }
"github:lightpanda-io/browser" = { version = "latest", os = ["linux", "macos"] }
"go:github.com/babarot/gomi" = "latest"
"go:github.com/k1LoW/git-wt" = "latest"
"go:github.com/syou6162/cchook" = "latest"
"go:github.com/Warashi/cage" = { version = "latest", os = ["linux", "macos"] }
"go:github.com/x-motemen/ghq" = "latest"
"npm:@openai/codex" = "latest"
"npm:agent-browser" = "latest"
"npm:opencode-ai" = "latest"
"npm:rulesync" = "latest"
"pipx:llmstxt2skill" = "latest"
"pipx:edge-tts" = "latest"



[settings]
trusted_config_paths = [
    "~/ghq",
]

[settings.npm]
package_manager = "bun"

[env]
# v3.13.0 broken now https://github.com/luarocks/luarocks/issues/1851
LUAROCKS_VERSION = "3.12.2"

[tasks.sync-rule]
description = "Sync agents' rules from claude code to others"
run = 'rulesync import -t claudecode -f "*" -V; rulesync generate -t "codexcli,opencode" -f "*" -V'

[tasks.sync-rule-global]
description = "Sync agents' rules from claude code to others"
run = 'rulesync import -g -t claudecode -f "*" -V; rulesync generate -g -t "codexcli,opencode" -f "*" -V'
